# ----------------------------
# Makefile Options
# ----------------------------

# export PATH=/Users/benji/CEdev/bin:$PATH

NAME = DOOM84
ICON = icon.png
DESCRIPTION = "Doom port for TI-84 Plus CE"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
